/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2010
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/


/*******************************************************************************
 *
 * Filename:
 * ---------
 * IniDefine.h
 *
 * Project:
 * --------
 *
 *
 * Description:
 * ------------
 *
 *
 * Author:
 * -------
 * Cole Xing
 *
 *------------------------------------------------------------------------------
 * $Revision:
 * $Modtime:
 * $Log:
 *
 *******************************************************************************/
#define INI_FILE_NAME TEXT("config.ini")
#define INI_TYPE_SYSTEM TEXT("SYSTEM")
#define INI_TYPE_USER TEXT("USER")

// Home
#define INI_KEY_COM TEXT("COM")
#define INI_KEY_COM_DEFAULT TEXT("COM1:")

// Settings Video
#define INI_KEY_VIDEO_BRIGHTNESS_NAME		TEXT("BRI")
#define INI_KEY_VIDEO_BRIGHTNESS_DEFAULT	TEXT("50")

#define INI_KEY_VIDEO_CONTRAST_NAME			TEXT("CON")
#define INI_KEY_VIDEO_CONTRAST_DEFAULT		TEXT("50")

#define INI_KEY_VIDEO_HUE_NAME				TEXT("HUE")
#define INI_KEY_VIDEO_HUE_DEFAULT			TEXT("0")

#define INI_KEY_VIDEO_SATUTATION_NAME		TEXT("SAT")
#define INI_KEY_VIDEO_SATUTATION_DEFAULT	TEXT("50")

#define INI_KEY_VIDEO_BACKLIGHT_NAME		TEXT("BAC")
#define INI_KEY_VIDEO_BACKLIGHT_DEFAULT		TEXT("5")


// Settings Audio
#define INI_KEY_AUDIO_VOLUME_NAME		TEXT("VOL")
#define INI_KEY_AUDIO_VOLUME_DEFAULT	TEXT("50")

#define INI_KEY_AUDIO_BASS_NAME		TEXT("BAS")
#define INI_KEY_AUDIO_BASS_DEFAULT	TEXT("50")

#define INI_KEY_AUDIO_TREBLE_NAME		TEXT("TRE")
#define INI_KEY_AUDIO_TREBLE_DEFAULT	TEXT("50")

#define INI_KEY_AUDIO_BALANCE_NAME		TEXT("BAL")
#define INI_KEY_AUDIO_BALANCE_DEFAULT	TEXT("0")

#define INI_KEY_AUDIO_EQ_NAME			TEXT("EQ")
#define INI_KEY_AUDIO_EQ_DEFAULT		TEXT("0")

#define INI_KEY_AUDIO_KEYBEEP_NAME		TEXT("KEY")
#define INI_KEY_AUDIO_KEYBEEP_DEFAULT	TEXT("1")

// Setting Logo
#define INI_KEY_LOGO_LOGO_INDEX		TEXT("LOG")
#define INI_KEY_LOGO_LOGO_INDEX_DEFAULT	TEXT("0")

// Setting Time
#define INI_KEY_TIME_TIMEFORMAT_NAME		TEXT("TIM")
#define INI_KEY_TIME_TIMEFORMAT_DEFAULT	TEXT("1")

#define INI_KEY_TIME_AUTOTIME_NAME		TEXT("AUT")
#define INI_KEY_TIME_AUTOTIME_DEFAULT	TEXT("1")

#define INI_KEY_CLOSE_HOME              TEXT("CLOSE")

#define INI_KEY_FRONT_HOME              TEXT("FRONT")
#define INI_KEY_REAR_HOME              TEXT("REAR")

// Setting SYS
#define INI_KEY_SYS_NAVIPATH_NAME		TEXT("GPS_E")
#define INI_KEY_SYS_NAVIPATH_DEFAULT	TEXT("\\SDMMC\\Navione\\navione.exe")

#define INI_KEY_SYS_LANGUAGE_NAME		TEXT("LAN")
#define INI_KEY_SYS_LANGUAGE_DEFAULT	TEXT("1")  //0:En, 1:SC, 2:TC

#define INI_KEY_SYS_CALIBRATION         TEXT("CALIBRATION")
#define INI_KEY_SYS_CALIBRATION_DEFAULT	TEXT("0")  //0:En, 1:SC, 2:TC


// MMP VDO SIZE W+H
#define INI_MMP_VDO_WIDTH		       TEXT("VDO_W")
#define INI_MMP_VDO_WIDTH_DEFAULT	TEXT("800")

#define INI_MMP_VDO_HEIGHT	       TEXT("VDO_H")
#define INI_MMP_VDO_HEIGHT_DEFAULT	 TEXT("480")

#define INI_MMP_TASKBAR_SHOW            TEXT("TaskBar Show")
#define INI_MMP_TASKBAR_SHOW_DEFAULT    TEXT("0")  //1:Active, 0:no-active

#define INI_MMP_BLACK_UI_LAYER         TEXT("Black UILayer")
#define INI_MMP_BLACK_UI_LAYER_DEFAULT    TEXT("1")  //1:Active, 0:no-active

#define INI_MMP_DVPCLOSE        TEXT("DVPCLOSE")
#define INI_MMP_DVPCLOSE_DEFAULT  TEXT("1")

#define INI_KEY_SYS_LANGUAGE_NAME		TEXT("LAN")
#define INI_KEY_SYS_LANGUAGE_DEFAULT	TEXT("1")  //0:En, 1:SC, 2:TC

#define INI_DVP_CD_RIP_DEVICE				TEXT("CDRip Device")
#define INI_DVP_CD_RIP_DEVICE_DEFAULT		TEXT("2") //1:Flash Disk, 2:USB Hard Disk, 3:Storage Card

//MMP TEST
#define INI_MMP_TEST           TEXT("RandomKey")
#define INI_MMP_TEST_DEFAULE   TEXT("0")



#define HOME_CFG_FILE_NAME TEXT("HomeCfg.ini")
#define HOME_CFG_FILE_NAME_3353 TEXT("HomeCfg3353.ini")

#define HOME_CFG_TYPE_BUTTON TEXT("HomeButton")
#define HOME_CFG_TYPE_BUTTON_X TEXT("HomeButton%d")

#define HOME_CFG_KEY_TOTAL TEXT("TotalButton")
#define HOME_CFG_KEY_BUTTONS_PER_ROW TEXT("ButtonPerRow")
#define HOME_CFG_KEY_ROWS_PER_PAGE TEXT("RowsPerPage")
#define HOME_CFG_KEY_TEXT TEXT("Text")
#define HOME_CFG_KEY_ICON_NORMAL TEXT("IconNormal")
#define HOME_CFG_KEY_ICON_DOWN TEXT("IconDown")
#define HOME_CFG_KEY_EXE TEXT("Exe")
#define HOME_CFG_KEY_ACTION TEXT("Action")
#define HOME_CFG_KEY_PATH TEXT("Path")
#define HOME_CFG_KEY_RUN_PARAM TEXT("RunParam")
#define HOME_CFG_KEY_AUTO_RUN_PARAM TEXT("AutoRunParam")

#define HOME_CFG_GPS_BUTTON TEXT("$GPS")

#define HOME_CFG_TYPE_OVERLAY_EXE TEXT("OverlayExe")
#define HOME_CFG_KEY_AUTO_RUN TEXT("AutoRun")

#define LANGUAGE_CFG_FILE_NAME     TEXT("LanguageCfg.ini")
#define LANGUAGE_CFG_LANGUAGE      TEXT("Language")
#define LANGUAGE_CFG_LANGUAGE_X    TEXT("Support_Language%d")
#define LANGUAGE_CFG_NOT_SUPPORT_LANGUAGE      TEXT("Do_Not_Support_Language")

#define LANGUAGE_CFG_LANGUAGE_TOTAL      TEXT("TotalLanguage")
#define LANGUAGE_CFG_LANGUAGE_START_CODE TEXT("StartCode")
#define LANGUAGE_CFG_LANGUAGE_END_CODE   TEXT("EndCode")


#define LANGUAGE_CFG_DO_NOT_REPLACE_CODE   TEXT("ReplaceCode")



//UI to Reg Mapping
#define VIDEO_BRIGHTNESS_UI_MIN    0
#define VIDEO_BRIGHTNESS_UI_MAX    100
#define VIDEO_BRIGHTNESS_MIN       0x00
#define VIDEO_BRIGHTNESS_MAX       100 //0xFFFFFFFF

#define VIDEO_CONTRAST_UI_MIN    0
#define VIDEO_CONTRAST_UI_MAX    100
#define VIDEO_CONTRAST_MIN       0x00
#define VIDEO_CONTRAST_MAX       100 //0xFFFFFFFF

#define VIDEO_HUE_UI_MIN    0
#define VIDEO_HUE_UI_MAX    100
#define VIDEO_HUE_MIN       0x00
#define VIDEO_HUE_MAX       100 //0xFFFFFFFF

#define VIDEO_SATUTATION_UI_MIN    0
#define VIDEO_SATUTATION_UI_MAX    100
#define VIDEO_SATUTATION_MIN       0x00
#define VIDEO_SATUTATION_MAX       100 //0xFFFFFFFF

#define VIDEO_BACKLIGHT_UI_MIN    0
#define VIDEO_BACKLIGHT_UI_MAX    10
#define VIDEO_BACKLIGHT_MIN       10 //0x00
#define VIDEO_BACKLIGHT_MAX       100 // 0xFFFFFFFF


#define AUDIO_VOLUME_UI_MIN    0
#define AUDIO_VOLUME_UI_MAX    100
#define AUDIO_VOLUME_MIN       0x00
#define AUDIO_VOLUME_MAX       0xFFFFFFFF

#define AUDIO_BASS_UI_MIN    -50
#define AUDIO_BASS_UI_MAX    50
#define AUDIO_BASS_MIN       0x00
#define AUDIO_BASS_MAX       0xFFFFFFFF

#define AUDIO_TREBLE_UI_MIN    -50
#define AUDIO_TREBLE_UI_MAX    50
#define AUDIO_TREBLE_MIN       0x00
#define AUDIO_TREBLE_MAX       0xFFFFFFFF

#define AUDIO_BALANCE_UI_MIN    -50
#define AUDIO_BALANCE_UI_MAX    50
#define AUDIO_BALANCE_MIN       0x00
#define AUDIO_BALANCE_MAX       0xFFFFFFFF
