/********************************************************************************************

*     LEGAL DISCLAIMER

*

*     (Header of MediaTek Software/Firmware Release or Documentation)

*

*     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES

*     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED

*     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS

*     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,

*     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR

*     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY

*     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,

*     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK

*     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO

*     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION

*     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.

*

*     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH

*     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,

*     TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE

*     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.

*

*     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS

*     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.

************************************************************************************************/

/******************************************************************************

* [File]			tvd_drv.h

* [Version]        	v1.0

* [Revision Date] 2011-03-08

* [Author]		changxu chen, changxu.chen@mediatek.com, mtk40136, 82629, 2011-03-08

* [Description]	

* [Copyright]

*    Copyright (C) 2011 MediaTek Incorporation. All Rights Reserved.

******************************************************************************/

#ifndef __FSC_TVD_H__

#define __FSC_TVD_H__

BOOL  TvdPreInit(HWND hAppWnd);

BOOL TvdInit(HWND);
BOOL TvdConfig(VOID);
BOOL TvdStart(VOID);
BOOL TvdStop(BOOL);
VOID TvdDeinit(VOID);
BOOL TvdSignalIsOn(VOID);


extern DWORD g_dwVdoFrameWidth;
extern DWORD g_dwVdoFrameHeight;

#endif


